
import Project.ConnectionProvider;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class Admin_Update_People_Information extends javax.swing.JFrame {

    /**
     * Creates new form Update_People_Information_List
     */
    public Admin_Update_People_Information() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        JTextField1 = new javax.swing.JTextField();
        JTextField2 = new javax.swing.JTextField();
        JTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(280, 150));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toppng.com-set-up-svg-icon-free-settings-icon-black-980x978.png"))); // NOI18N
        jLabel1.setText("Update People's Information ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("People's Registration No.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 112, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Father Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Date Of Birth");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("NID No");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Gender");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Blood Group");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Address");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 570, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Contact Number");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 640, -1, -1));

        JTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JTextField1.setText("Enter Reg Id...");
        JTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(JTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 340, 40));

        JTextField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JTextField2.setText("Enter Name...");
        jPanel1.add(JTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 340, 40));

        JTextField3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(JTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 340, 40));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 340, 40));

        jTextField5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField5.setText("Enter NID Number...");
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 340, 40));

        jTextField6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 140, 40));

        jTextField7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 340, 40));

        jTextField8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, 340, 40));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Save .png"))); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 780, -1, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cross- 20.png"))); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 780, 100, 40));

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField9.setText("Enter Contact No...");
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 630, 340, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Nationality");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 690, 90, 30));

        jTextField10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 690, 340, 40));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 100, 40));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete - little.png"))); // NOI18N
        jButton4.setText("Reset All");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 780, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 904));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //TODO add your handling code here:
       
        String did = JTextField1.getText();
        String dname= JTextField2.getText();
        String dspec= JTextField3.getText();
        String DateofBirth = jTextField4.getText();
        String NIDNo = jTextField5.getText();
        String Gender = jTextField6.getText();
        String BloodGroup = jTextField7.getText();
        String Address = jTextField8.getText();
        String ContactNumber = jTextField9.getText();
        String Nationality = jTextField10.getText();
        
         try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/censusmanagement", "root", "");

            String sql = "update `addinformation` SET `Name`='" + dname + "',`FatherName`='" + dspec + "',`DateofBirth`='" + DateofBirth + "',`NIDNo`='" + NIDNo + "',`Gender`='" + Gender + "',`BloodGroup`='" + BloodGroup + "',`Address`='" + Address + "',`ContactNumber`='" + ContactNumber + "',`Nationality`='" + Nationality + "'WHERE RegID='" + did + "'";
            //String sql = "update `addinformation` SET `Name`='"+dname+"',`FatherName`='"+dspec+"'WHERE RegID='"+did+"'";
            //here if did!= any id available in the database show error

            PreparedStatement ptstmt = conn.prepareStatement(sql);
            ptstmt.execute();
            if (sql.contains(did) != true) {
                //System.out.println();
                JOptionPane.showMessageDialog(null, "No Such record");
            } else {
                JOptionPane.showMessageDialog(null, "Record updated successfully");
            }

        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        JTextField2.setText("");
        JTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          
        
        
        String RegID = JTextField1.getText();
        String Name = JTextField2.getText();
        String NIDNo = jTextField5.getText();
        String ContactNumber = jTextField9.getText();
        
        try{
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement();
            //ResultSet rs = st.executeQuery("select *from addinformation where RegID or ContactNumber='"+RegID+","+ContactNumber+"'"); 
            //ResultSet rs = st.executeQuery("select *from addinformation where RegID or ContactNumber='"+RegID+","+ContactNumber+"'"); 
            ResultSet rs1 = st.executeQuery("select *from addinformation where RegID='"+RegID+"' or Name='"+Name+"' or NIDNo='"+NIDNo+"' or ContactNumber='"+ContactNumber+"' "); 
            //ResultSet rs2 = st.executeQuery("select *from addinformation where name='"+Name+"'"); 
            //ResultSet rs3 = st.executeQuery("select *from addinformation where DateofBirth='"+DateofBirth+"'"); 
            //ResultSet rs4 = st.executeQuery("select *from addinformation where Address='"+Address+"'"); 
            //ResultSet rs5 = st.executeQuery("select *from addinformation where ContactNumber='"+ContactNumber+"'"); 
            if(rs1.next())
            {
                JTextField1.setText(rs1.getString(1));
                JTextField2.setText(rs1.getString(2));
                JTextField3.setText(rs1.getString(3));
                jTextField4.setText(rs1.getString(4));
                jTextField5.setText(rs1.getString(5));
                jTextField6.setText(rs1.getString(6));
                jTextField7.setText(rs1.getString(7));
                jTextField8.setText(rs1.getString(8));
                jTextField9.setText(rs1.getString(9));
                jTextField10.setText(rs1.getString(10));
                JTextField1.setEditable(true);          
                JTextField2.setEditable(true);          
                jTextField5.setEditable(true);          
                jTextField9.setEditable(true);          
            }
            
            /*else if(rs2.next())
            {
                jTextField1.setText(rs2.getString(1));
                jTextField3.setText(rs2.getString(3));
                jTextField4.setText(rs2.getString(4));
                jTextField5.setText(rs2.getString(5));
                jTextField6.setText(rs2.getString(6));
                jTextField7.setText(rs2.getString(7));
                jTextField8.setText(rs2.getString(8));
                jTextField9.setText(rs2.getString(9));
                jTextField10.setText(rs2.getString(10));
                jTextField11.setText(rs1.getString(11));
                jTextField2.setEditable(true);          
            }
            
            else if(rs3.next())
            {
                jTextField1.setText(rs3.getString(1));
                jTextField2.setText(rs3.getString(2));
                jTextField3.setText(rs3.getString(3));
                jTextField5.setText(rs3.getString(5));
                jTextField6.setText(rs3.getString(6));
                jTextField7.setText(rs3.getString(7));
                jTextField8.setText(rs3.getString(8));
                jTextField9.setText(rs3.getString(9));
                jTextField10.setText(rs3.getString(10));
                jTextField11.setText(rs1.getString(11));
                jTextField4.setEditable(true);          
            }
            
            else if(rs4.next())
            {
                jTextField1.setText(rs4.getString(1));
                jTextField2.setText(rs4.getString(2));
                jTextField3.setText(rs4.getString(3));
                jTextField4.setText(rs4.getString(4));
                jTextField5.setText(rs4.getString(5));
                jTextField6.setText(rs4.getString(6));
                jTextField7.setText(rs4.getString(7));
                jTextField9.setText(rs4.getString(9));
                jTextField10.setText(rs4.getString(10));
                jTextField11.setText(rs1.getString(11));
                jTextField8.setEditable(true);          
            }
            
            else if(rs5.next())
            {
                jTextField1.setText(rs5.getString(1));
                jTextField2.setText(rs5.getString(2));
                jTextField3.setText(rs5.getString(3));
                jTextField4.setText(rs5.getString(4));
                jTextField5.setText(rs5.getString(5));
                jTextField6.setText(rs5.getString(6));
                jTextField7.setText(rs5.getString(7));
                jTextField8.setText(rs5.getString(8));
                jTextField10.setText(rs5.getString(10));
                jTextField11.setText(rs1.getString(11));
                jTextField9.setEditable(true);          
            }*/
            else
            {
                JOptionPane.showMessageDialog(null, "Information Doesn't Exit!!!");
            }
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void JTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField1ActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_JTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JTextField1.setText("");
        JTextField2.setText("");
        JTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Update_People_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Update_People_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Update_People_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Update_People_Information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Update_People_Information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextField1;
    private javax.swing.JTextField JTextField2;
    private javax.swing.JTextField JTextField3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
